runtime: go
api_version: go1

handlers:
- url: /.*
  script: app.go

# automatic_scaling:
#   max_instances: 1

manual_scaling:
  instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.9
#   disk_size_gb: 10
